apiVersion: v1
kind: Service
metadata:
  name: {{ include "bolt-portal-chart-tmp.fullname" . }}
  labels:
    {{- include "bolt-portal-chart-tmp.labels" . | nindent 4 }}
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "bolt-portal-chart-tmp.selectorLabels" . | nindent 4 }}
